//! Physical key capability set.
//!
//! This module defines the *explicit* set of physical keys Ferrokey is able to
//! emit. It is deliberately **not** a raw `1..240` scan of Linux input codes:
//! the capability set is deterministic, auditable and maps 1:1 onto the
//! `KEY_*` codes of the Linux input subsystem.
//!
//! The distinction between `PhysicalKey` (what key is on the board),
//! `LogicalKey` (what that key means in the active layout) and
//! `TextSymbol` (the character produced) lives in [`crate::layout`].

use serde::{Deserialize, Deserializer, Serialize, Serializer};

/// A physical key on the virtual keyboard, identified by its Linux input
/// code (`KEY_*` from `linux/input-event-codes.h`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum PhysicalKey {
    // ── Alphanumeric row ────────────────────────────────────────────────
    Escape,
    D1,
    D2,
    D3,
    D4,
    D5,
    D6,
    D7,
    D8,
    D9,
    D0,
    Minus,
    Equal,
    Backspace,
    Tab,
    Q,
    W,
    E,
    R,
    T,
    Y,
    U,
    I,
    O,
    P,
    LeftBracket,
    RightBracket,
    Enter,
    LeftCtrl,
    A,
    S,
    D,
    F,
    G,
    H,
    J,
    K,
    L,
    Semicolon,
    Apostrophe,
    Grave,
    LeftShift,
    Backslash,
    Z,
    X,
    C,
    V,
    B,
    N,
    M,
    Comma,
    Dot,
    Slash,
    RightShift,
    LeftAlt,
    Space,
    CapsLock,
    IntlBackslash,

    // ── Function row ────────────────────────────────────────────────────
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,

    // ── Modifiers (right-hand column) ───────────────────────────────────
    RightCtrl,
    RightAlt,
    LeftMeta,
    RightMeta,
    Menu,
    Compose,
    SysRq,
    Pause,

    // ── Lock keys ───────────────────────────────────────────────────────
    NumLock,
    ScrollLock,

    // ── Navigation / editing cluster ────────────────────────────────────
    Insert,
    Delete,
    Home,
    End,
    PageUp,
    PageDown,
    Up,
    Down,
    Left,
    Right,

    // ── Numeric keypad ──────────────────────────────────────────────────
    Kp0,
    Kp1,
    Kp2,
    Kp3,
    Kp4,
    Kp5,
    Kp6,
    Kp7,
    Kp8,
    Kp9,
    KpDecimal,
    KpEnter,
    KpAdd,
    KpSubtract,
    KpMultiply,
    KpDivide,
    KpEqual,
    KpComma,
    KpLeftParen,
    KpRightParen,

    // ── Media / system ──────────────────────────────────────────────────
    Mute,
    VolumeDown,
    VolumeUp,
    NextSong,
    PreviousSong,
    StopCd,
    PlayPause,
    Record,
    Rewind,
    FastForward,
    EjectCd,
    BrightnessDown,
    BrightnessUp,
    Power,
    Sleep,
    Wakeup,
    Back,
    Forward,
    Refresh,
    HomePage,
    Mail,
    Calculator,
    Bookmarks,
    Computer,
    Search,
    Help,
}

impl PhysicalKey {
    /// The Linux input event code (`KEY_*`) for this key.
    ///
    /// These constants come from `include/uapi/linux/input-event-codes.h`.
    pub const fn linux_code(self) -> u32 {
        use PhysicalKey::*;
        match self {
            Escape => 1,
            D1 => 2,
            D2 => 3,
            D3 => 4,
            D4 => 5,
            D5 => 6,
            D6 => 7,
            D7 => 8,
            D8 => 9,
            D9 => 10,
            D0 => 11,
            Minus => 12,
            Equal => 13,
            Backspace => 14,
            Tab => 15,
            Q => 16,
            W => 17,
            E => 18,
            R => 19,
            T => 20,
            Y => 21,
            U => 22,
            I => 23,
            O => 24,
            P => 25,
            LeftBracket => 26,
            RightBracket => 27,
            Enter => 28,
            LeftCtrl => 29,
            A => 30,
            S => 31,
            D => 32,
            F => 33,
            G => 34,
            H => 35,
            J => 36,
            K => 37,
            L => 38,
            Semicolon => 39,
            Apostrophe => 40,
            Grave => 41,
            LeftShift => 42,
            Backslash => 43,
            Z => 44,
            X => 45,
            C => 46,
            V => 47,
            B => 48,
            N => 49,
            M => 50,
            Comma => 51,
            Dot => 52,
            Slash => 53,
            RightShift => 54,
            LeftAlt => 56,
            Space => 57,
            CapsLock => 58,
            F1 => 59,
            F2 => 60,
            F3 => 61,
            F4 => 62,
            F5 => 63,
            F6 => 64,
            F7 => 65,
            F8 => 66,
            F9 => 67,
            F10 => 68,
            NumLock => 69,
            ScrollLock => 70,
            Kp7 => 71,
            Kp8 => 72,
            Kp9 => 73,
            KpMultiply => 55,
            KpSubtract => 74,
            Kp4 => 75,
            Kp5 => 76,
            Kp6 => 77,
            KpAdd => 78,
            Kp1 => 79,
            Kp2 => 80,
            Kp3 => 81,
            Kp0 => 82,
            KpDecimal => 83,
            IntlBackslash => 86,
            F11 => 87,
            F12 => 88,
            KpComma => 95,
            KpEnter => 96,
            RightCtrl => 97,
            KpDivide => 98,
            SysRq => 99,
            RightAlt => 100,
            KpLeftParen => 179,
            KpRightParen => 180,
            Home => 102,
            Up => 103,
            PageUp => 104,
            Left => 105,
            Right => 106,
            End => 107,
            Down => 108,
            PageDown => 109,
            Insert => 110,
            Delete => 111,
            Mute => 113,
            VolumeDown => 114,
            VolumeUp => 115,
            KpEqual => 117,
            Pause => 119,
            LeftMeta => 125,
            RightMeta => 126,
            Compose => 127,
            Menu => 139,
            Sleep => 142,
            Wakeup => 143,
            F13 => 183,
            F14 => 184,
            F15 => 185,
            F16 => 186,
            F17 => 187,
            F18 => 188,
            F19 => 189,
            F20 => 190,
            F21 => 191,
            F22 => 192,
            F23 => 193,
            F24 => 194,
            FastForward => 208,
            Power => 116,
            Back => 158,
            Forward => 159,
            StopCd => 166,
            Record => 167,
            Rewind => 168,
            EjectCd => 161,
            NextSong => 163,
            PreviousSong => 165,
            PlayPause => 164,
            BrightnessDown => 224,
            BrightnessUp => 225,
            Refresh => 173,
            HomePage => 172,
            Mail => 155,
            Calculator => 140,
            Bookmarks => 156,
            Computer => 157,
            Search => 217,
            Help => 138,
        }
    }

    /// Stable, human-readable identifier (used in protocol logs, receipts and
    /// layout data files).
    pub const fn name(self) -> &'static str {
        use PhysicalKey::*;
        match self {
            Escape => "escape",
            D1 => "1",
            D2 => "2",
            D3 => "3",
            D4 => "4",
            D5 => "5",
            D6 => "6",
            D7 => "7",
            D8 => "8",
            D9 => "9",
            D0 => "0",
            Minus => "minus",
            Equal => "equal",
            Backspace => "backspace",
            Tab => "tab",
            Q => "q",
            W => "w",
            E => "e",
            R => "r",
            T => "t",
            Y => "y",
            U => "u",
            I => "i",
            O => "o",
            P => "p",
            LeftBracket => "left-bracket",
            RightBracket => "right-bracket",
            Enter => "enter",
            LeftCtrl => "left-ctrl",
            A => "a",
            S => "s",
            D => "d",
            F => "f",
            G => "g",
            H => "h",
            J => "j",
            K => "k",
            L => "l",
            Semicolon => "semicolon",
            Apostrophe => "apostrophe",
            Grave => "grave",
            LeftShift => "left-shift",
            Backslash => "backslash",
            Z => "z",
            X => "x",
            C => "c",
            V => "v",
            B => "b",
            N => "n",
            M => "m",
            Comma => "comma",
            Dot => "dot",
            Slash => "slash",
            RightShift => "right-shift",
            LeftAlt => "left-alt",
            Space => "space",
            CapsLock => "caps-lock",
            IntlBackslash => "intl-backslash",
            F1 => "f1",
            F2 => "f2",
            F3 => "f3",
            F4 => "f4",
            F5 => "f5",
            F6 => "f6",
            F7 => "f7",
            F8 => "f8",
            F9 => "f9",
            F10 => "f10",
            F11 => "f11",
            F12 => "f12",
            F13 => "f13",
            F14 => "f14",
            F15 => "f15",
            F16 => "f16",
            F17 => "f17",
            F18 => "f18",
            F19 => "f19",
            F20 => "f20",
            F21 => "f21",
            F22 => "f22",
            F23 => "f23",
            F24 => "f24",
            RightCtrl => "right-ctrl",
            RightAlt => "right-alt",
            LeftMeta => "left-meta",
            RightMeta => "right-meta",
            Menu => "menu",
            Compose => "compose",
            SysRq => "sysrq",
            Pause => "pause",
            NumLock => "num-lock",
            ScrollLock => "scroll-lock",
            Insert => "insert",
            Delete => "delete",
            Home => "home",
            End => "end",
            PageUp => "page-up",
            PageDown => "page-down",
            Up => "up",
            Down => "down",
            Left => "left",
            Right => "right",
            Kp0 => "kp0",
            Kp1 => "kp1",
            Kp2 => "kp2",
            Kp3 => "kp3",
            Kp4 => "kp4",
            Kp5 => "kp5",
            Kp6 => "kp6",
            Kp7 => "kp7",
            Kp8 => "kp8",
            Kp9 => "kp9",
            KpDecimal => "kp-decimal",
            KpEnter => "kp-enter",
            KpAdd => "kp-add",
            KpSubtract => "kp-subtract",
            KpMultiply => "kp-multiply",
            KpDivide => "kp-divide",
            KpEqual => "kp-equal",
            KpComma => "kp-comma",
            KpLeftParen => "kp-left-paren",
            KpRightParen => "kp-right-paren",
            Mute => "mute",
            VolumeDown => "volume-down",
            VolumeUp => "volume-up",
            NextSong => "next-song",
            PreviousSong => "previous-song",
            StopCd => "stop",
            PlayPause => "play-pause",
            Record => "record",
            Rewind => "rewind",
            FastForward => "fast-forward",
            EjectCd => "eject",
            BrightnessDown => "brightness-down",
            BrightnessUp => "brightness-up",
            Power => "power",
            Sleep => "sleep",
            Wakeup => "wakeup",
            Back => "back",
            Forward => "forward",
            Refresh => "refresh",
            HomePage => "homepage",
            Mail => "mail",
            Calculator => "calculator",
            Bookmarks => "bookmarks",
            Computer => "computer",
            Search => "search",
            Help => "help",
        }
    }

    /// Resolve a name (as produced by [`PhysicalKey::name`]) back into a key.
    /// Accepts a small set of aliases for convenience.
    pub fn from_name(name: &str) -> Option<Self> {
        use PhysicalKey::*;
        Some(match name {
            "escape" | "esc" => Escape,
            "1" => D1,
            "2" => D2,
            "3" => D3,
            "4" => D4,
            "5" => D5,
            "6" => D6,
            "7" => D7,
            "8" => D8,
            "9" => D9,
            "0" => D0,
            "minus" | "-" => Minus,
            "equal" | "=" => Equal,
            "backspace" => Backspace,
            "tab" => Tab,
            "q" => Q,
            "w" => W,
            "e" => E,
            "r" => R,
            "t" => T,
            "y" => Y,
            "u" => U,
            "i" => I,
            "o" => O,
            "p" => P,
            "left-bracket" | "[" => LeftBracket,
            "right-bracket" | "]" => RightBracket,
            "enter" | "return" => Enter,
            "left-ctrl" | "lctrl" => LeftCtrl,
            "a" => A,
            "s" => S,
            "d" => D,
            "f" => F,
            "g" => G,
            "h" => H,
            "j" => J,
            "k" => K,
            "l" => L,
            "semicolon" | ";" => Semicolon,
            "apostrophe" | "'" => Apostrophe,
            "grave" | "`" => Grave,
            "left-shift" | "lshift" => LeftShift,
            "backslash" | "\\" => Backslash,
            "z" => Z,
            "x" => X,
            "c" => C,
            "v" => V,
            "b" => B,
            "n" => N,
            "m" => M,
            "comma" | "," => Comma,
            "dot" | "." => Dot,
            "slash" | "/" => Slash,
            "right-shift" | "rshift" => RightShift,
            "left-alt" | "lalt" => LeftAlt,
            "space" => Space,
            "caps-lock" | "capslock" => CapsLock,
            "intl-backslash" | "102nd" | "<" => IntlBackslash,
            "f1" => F1,
            "f2" => F2,
            "f3" => F3,
            "f4" => F4,
            "f5" => F5,
            "f6" => F6,
            "f7" => F7,
            "f8" => F8,
            "f9" => F9,
            "f10" => F10,
            "f11" => F11,
            "f12" => F12,
            "f13" => F13,
            "f14" => F14,
            "f15" => F15,
            "f16" => F16,
            "f17" => F17,
            "f18" => F18,
            "f19" => F19,
            "f20" => F20,
            "f21" => F21,
            "f22" => F22,
            "f23" => F23,
            "f24" => F24,
            "right-ctrl" | "rctrl" => RightCtrl,
            "right-alt" | "ralt" | "altgr" => RightAlt,
            "left-meta" | "lmeta" | "super" | "left-super" | "win" => LeftMeta,
            "right-meta" | "rmeta" | "right-super" => RightMeta,
            "menu" => Menu,
            "compose" => Compose,
            "sysrq" => SysRq,
            "pause" => Pause,
            "num-lock" | "numlock" => NumLock,
            "scroll-lock" | "scrolllock" => ScrollLock,
            "insert" => Insert,
            "delete" => Delete,
            "home" => Home,
            "end" => End,
            "page-up" | "pgup" => PageUp,
            "page-down" | "pgdn" => PageDown,
            "up" => Up,
            "down" => Down,
            "left" => Left,
            "right" => Right,
            "kp0" => Kp0,
            "kp1" => Kp1,
            "kp2" => Kp2,
            "kp3" => Kp3,
            "kp4" => Kp4,
            "kp5" => Kp5,
            "kp6" => Kp6,
            "kp7" => Kp7,
            "kp8" => Kp8,
            "kp9" => Kp9,
            "kp-decimal" | "kp-dot" => KpDecimal,
            "kp-enter" => KpEnter,
            "kp-add" | "kp-plus" => KpAdd,
            "kp-subtract" | "kp-minus" => KpSubtract,
            "kp-multiply" | "kp-asterisk" => KpMultiply,
            "kp-divide" | "kp-slash" => KpDivide,
            "kp-equal" => KpEqual,
            "kp-comma" => KpComma,
            "kp-left-paren" => KpLeftParen,
            "kp-right-paren" => KpRightParen,
            "mute" => Mute,
            "volume-down" => VolumeDown,
            "volume-up" => VolumeUp,
            "next-song" | "next" => NextSong,
            "previous-song" | "prev" => PreviousSong,
            "stop" | "stopcd" => StopCd,
            "play-pause" | "play" => PlayPause,
            "record" => Record,
            "rewind" => Rewind,
            "fast-forward" => FastForward,
            "eject" | "ejectcd" => EjectCd,
            "brightness-down" => BrightnessDown,
            "brightness-up" => BrightnessUp,
            "power" => Power,
            "sleep" => Sleep,
            "wakeup" => Wakeup,
            "back" => Back,
            "forward" => Forward,
            "refresh" => Refresh,
            "homepage" => HomePage,
            "mail" => Mail,
            "calculator" => Calculator,
            "bookmarks" => Bookmarks,
            "computer" => Computer,
            "search" => Search,
            "help" => Help,
            _ => return None,
        })
    }

    /// Whether this key is a modifier key (shift/ctrl/alt/altgr/meta).
    pub fn is_modifier(self) -> bool {
        self.modifier_kind().is_some()
    }

    /// Whether this key is a lock key (caps/num/scroll lock).
    pub fn is_lock_key(self) -> bool {
        matches!(
            self,
            PhysicalKey::CapsLock | PhysicalKey::NumLock | PhysicalKey::ScrollLock
        )
    }

    /// Resolve a linux input code back into a key, if it is part of the
    /// explicit capability set.
    pub fn from_linux_code(code: u32) -> Option<Self> {
        CAPABILITY_SET
            .iter()
            .find(|k| k.linux_code() == code)
            .copied()
    }
}

impl Serialize for PhysicalKey {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.name())
    }
}

impl<'de> Deserialize<'de> for PhysicalKey {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let s = String::deserialize(deserializer)?;
        PhysicalKey::from_name(&s)
            .ok_or_else(|| serde::de::Error::custom(format!("unknown physical key name: {s:?}")))
    }
}

/// The complete, explicit capability set advertised to the kernel.
///
/// This is what gets written into the uinput device's key bitmask — nothing
/// more, nothing less. It is deterministic and auditable by construction.
pub const CAPABILITY_SET: &[PhysicalKey] = &[
    // Alphanumerics + US punctuation row
    PhysicalKey::Escape,
    PhysicalKey::D1,
    PhysicalKey::D2,
    PhysicalKey::D3,
    PhysicalKey::D4,
    PhysicalKey::D5,
    PhysicalKey::D6,
    PhysicalKey::D7,
    PhysicalKey::D8,
    PhysicalKey::D9,
    PhysicalKey::D0,
    PhysicalKey::Minus,
    PhysicalKey::Equal,
    PhysicalKey::Backspace,
    PhysicalKey::Tab,
    PhysicalKey::Q,
    PhysicalKey::W,
    PhysicalKey::E,
    PhysicalKey::R,
    PhysicalKey::T,
    PhysicalKey::Y,
    PhysicalKey::U,
    PhysicalKey::I,
    PhysicalKey::O,
    PhysicalKey::P,
    PhysicalKey::LeftBracket,
    PhysicalKey::RightBracket,
    PhysicalKey::Enter,
    PhysicalKey::A,
    PhysicalKey::S,
    PhysicalKey::D,
    PhysicalKey::F,
    PhysicalKey::G,
    PhysicalKey::H,
    PhysicalKey::J,
    PhysicalKey::K,
    PhysicalKey::L,
    PhysicalKey::Semicolon,
    PhysicalKey::Apostrophe,
    PhysicalKey::Grave,
    PhysicalKey::Backslash,
    PhysicalKey::Z,
    PhysicalKey::X,
    PhysicalKey::C,
    PhysicalKey::V,
    PhysicalKey::B,
    PhysicalKey::N,
    PhysicalKey::M,
    PhysicalKey::Comma,
    PhysicalKey::Dot,
    PhysicalKey::Slash,
    PhysicalKey::Space,
    PhysicalKey::IntlBackslash,
    // Modifiers
    PhysicalKey::LeftShift,
    PhysicalKey::RightShift,
    PhysicalKey::LeftCtrl,
    PhysicalKey::RightCtrl,
    PhysicalKey::LeftAlt,
    PhysicalKey::RightAlt,
    PhysicalKey::LeftMeta,
    PhysicalKey::RightMeta,
    PhysicalKey::Menu,
    PhysicalKey::Compose,
    // Lock keys
    PhysicalKey::CapsLock,
    PhysicalKey::NumLock,
    PhysicalKey::ScrollLock,
    // Function row
    PhysicalKey::F1,
    PhysicalKey::F2,
    PhysicalKey::F3,
    PhysicalKey::F4,
    PhysicalKey::F5,
    PhysicalKey::F6,
    PhysicalKey::F7,
    PhysicalKey::F8,
    PhysicalKey::F9,
    PhysicalKey::F10,
    PhysicalKey::F11,
    PhysicalKey::F12,
    PhysicalKey::F13,
    PhysicalKey::F14,
    PhysicalKey::F15,
    PhysicalKey::F16,
    PhysicalKey::F17,
    PhysicalKey::F18,
    PhysicalKey::F19,
    PhysicalKey::F20,
    PhysicalKey::F21,
    PhysicalKey::F22,
    PhysicalKey::F23,
    PhysicalKey::F24,
    // Navigation / editing
    PhysicalKey::Insert,
    PhysicalKey::Delete,
    PhysicalKey::Home,
    PhysicalKey::End,
    PhysicalKey::PageUp,
    PhysicalKey::PageDown,
    PhysicalKey::Up,
    PhysicalKey::Down,
    PhysicalKey::Left,
    PhysicalKey::Right,
    // Numeric keypad
    PhysicalKey::Kp0,
    PhysicalKey::Kp1,
    PhysicalKey::Kp2,
    PhysicalKey::Kp3,
    PhysicalKey::Kp4,
    PhysicalKey::Kp5,
    PhysicalKey::Kp6,
    PhysicalKey::Kp7,
    PhysicalKey::Kp8,
    PhysicalKey::Kp9,
    PhysicalKey::KpDecimal,
    PhysicalKey::KpEnter,
    PhysicalKey::KpAdd,
    PhysicalKey::KpSubtract,
    PhysicalKey::KpMultiply,
    PhysicalKey::KpDivide,
    PhysicalKey::KpEqual,
    PhysicalKey::KpComma,
    PhysicalKey::KpLeftParen,
    PhysicalKey::KpRightParen,
    // Media / system
    PhysicalKey::Mute,
    PhysicalKey::VolumeDown,
    PhysicalKey::VolumeUp,
    PhysicalKey::NextSong,
    PhysicalKey::PreviousSong,
    PhysicalKey::StopCd,
    PhysicalKey::PlayPause,
    PhysicalKey::Record,
    PhysicalKey::Rewind,
    PhysicalKey::FastForward,
    PhysicalKey::EjectCd,
    PhysicalKey::BrightnessDown,
    PhysicalKey::BrightnessUp,
    PhysicalKey::Power,
    PhysicalKey::Sleep,
    PhysicalKey::Wakeup,
    PhysicalKey::Back,
    PhysicalKey::Forward,
    PhysicalKey::Refresh,
    PhysicalKey::HomePage,
    PhysicalKey::Mail,
    PhysicalKey::Calculator,
    PhysicalKey::Bookmarks,
    PhysicalKey::Computer,
    PhysicalKey::Search,
    PhysicalKey::Help,
];

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeSet;

    #[test]
    fn capability_set_is_dense_and_unique() {
        let codes: BTreeSet<u32> = CAPABILITY_SET.iter().map(|k| k.linux_code()).collect();
        assert_eq!(
            codes.len(),
            CAPABILITY_SET.len(),
            "duplicate linux codes in capability set"
        );
        // Every code must be a valid, non-zero evdev code < KEY_MAX (0x2ff).
        for &code in &codes {
            assert!(code > 0 && code < 0x2ff, "out-of-range code {code}");
        }
    }

    #[test]
    fn names_round_trip() {
        for &key in CAPABILITY_SET {
            let name = key.name();
            assert_eq!(
                PhysicalKey::from_name(name),
                Some(key),
                "name {name:?} does not round-trip"
            );
        }
    }

    #[test]
    fn modifiers_are_identified() {
        assert!(PhysicalKey::LeftShift.is_modifier());
        assert!(PhysicalKey::RightAlt.is_modifier());
        assert!(!PhysicalKey::A.is_modifier());
        assert!(!PhysicalKey::Space.is_modifier());
    }

    #[test]
    fn letters_have_expected_linux_codes() {
        assert_eq!(PhysicalKey::A.linux_code(), 30);
        assert_eq!(PhysicalKey::Q.linux_code(), 16);
        assert_eq!(PhysicalKey::Z.linux_code(), 44);
        assert_eq!(PhysicalKey::LeftCtrl.linux_code(), 29);
        assert_eq!(PhysicalKey::Space.linux_code(), 57);
        assert_eq!(PhysicalKey::F1.linux_code(), 59);
        assert_eq!(PhysicalKey::F24.linux_code(), 194);
    }
}
